# Generated by Django 5.1.4 on 2024-12-29 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='available_copies',
        ),
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(default='book_covers/default_cover.jpg', upload_to='book_covers/'),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='total_copies',
            field=models.PositiveIntegerField(),
        ),
    ]
