# Generated by Django 5.1.4 on 2024-12-29 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_userprofile1'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile1',
            name='borrowed_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userprofile1',
            name='hostel',
            field=models.CharField(max_length=50),
        ),
    ]
