# Generated by Django 5.1.4 on 2024-12-29 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_userprofile1_borrowed_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='borrowed_count',
            field=models.IntegerField(default=0),
        ),
    ]
