# Generated by Django 5.1.4 on 2024-12-29 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_userprofile_borrowed_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='borrowed_count',
        ),
        migrations.RemoveField(
            model_name='userprofile1',
            name='borrowed_count',
        ),
        migrations.AddField(
            model_name='book',
            name='borrowed_count',
            field=models.IntegerField(default=0),
        ),
    ]
